export const FETCH_REQUEST_CITY = 'FETCH_REQUEST_CUTY';
export const FETCH_SUCCESS_CITY = 'FETCH_SUCCESS_CITY';
export const FETCH_ERROR_CITY = 'FETCH_ERROR_CITY';

export const UPDATE_CITY = 'UPDATE_CITY';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const ERROR = 'ERROR';
export const ERROR_CLEAR = 'ERROR_CLEAR';

export const ASK_LOCATION = 'ASK_LOCATION';
export const ASK_LOCATION_ACCEPT = 'ASK_LOCATION_ACCEPT';
export const ASK_LOCATION_REJECT = 'ASK_LOCATION_REJECT';
