export const FETCH_REQUEST_CITIES = 'FETCH_REQUEST_CUTY';
export const FETCH_SUCCESS_CITIES = 'FETCH_SUCCESS_CITY';
export const FETCH_ERROR_CITIES = 'FETCH_ERROR_CUTY';
export const UPDATE_CITIES = 'UPDATE_CITIES';

export const LOADING_START_CITIES = 'LOADING_START_CITIES';
export const LOADING_END_CITIES = 'LOADING_END_CITIES';

export const ASK_LOCATION = 'ASK_LOCATION';
export const ASK_LOCATION_ACCEPT = 'ASK_LOCATION_ACCEPT';
export const ASK_LOCATION_REJECT = 'ASK_LOCATION_REJECT';
